# config.yml for WaterLinker version 1.0
# For more information on how to set up and use this plugin, visit https://docs.waterbroodje.nl/
# If you can't find the answer on that page, you can send me a DM on Discord, Timo#9435.
# I will only reply to questions when it's not on my documentation page, otherwise, your message will be ignored.

# The database credentials
database:
  address: ""
  port: 3306
  database: ""
  username: ""
  password: ""

# The information for the discord bot.
discord:
  token: "DISCORD-TOKEN"
  guild: true # If set to true, the command only works inside a guild.


# The roles you want to give in the Discord server when a user has a specific permission.
roles:
  enabled: false
  override: true # Highest permission in this list will be applied to the user.
  permissions:
    rank.mvp: "000000000000000000"
    rank.vip: "000000000000000000"